name: "circleci"
version: 2.0

orbs:
 android: circleci/android@4.0.1

jobs:
  build:
    executor: circleci/android
        
    steps:
      - checkout
      - run:
          command: ./gradlew build
